CREATE TABLE IF NOT EXISTS PERFIL(
    COD_PERFIL INT PRIMARY KEY NOT NULL,
    NOME_PERFIL VARCHAR(255) NOT NULL,
    STATUS INT NOT NULL
);

CREATE SEQUENCE PERFIL_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE TABLE IF NOT EXISTS USUARIO(
    COD_USUARIO INT PRIMARY KEY NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    NUMERO_TELEFONE VARCHAR(20),
    CPF VARCHAR(11) NOT NULL,
    COD_PERFIL INT,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL(COD_PERFIL)
);

CREATE SEQUENCE USUARIO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


